-- carbon.proposal definition

CREATE TABLE `proposal` (
  `pps_id` int NOT NULL AUTO_INCREMENT,
  `pps_id_production` int DEFAULT NULL,
  `proposal_number` varchar(50) NOT NULL,
  `num` bigint NOT NULL,
  `cod` char(2) NOT NULL,
  `create_date` datetime NOT NULL,
  `validity_date` datetime NOT NULL,
  `finished_date` datetime DEFAULT NULL,
  `status_cla_id` int NOT NULL,
  `amendments_status_cla` int DEFAULT NULL,
  `led_id` int DEFAULT NULL,
  `finantial_contact` tinyint NOT NULL DEFAULT '0',
  `finantial_contact_name` varchar(150) DEFAULT NULL,
  `finantial_contact_email` varchar(100) DEFAULT NULL,
  `finantial_contact_phone` varchar(45) DEFAULT NULL,
  `document_contact` tinyint NOT NULL DEFAULT '0',
  `document_contact_name` varchar(150) DEFAULT NULL,
  `document_contact_email` varchar(100) DEFAULT NULL,
  `document_contact_phone` varchar(45) DEFAULT NULL,
  `commercial_contact_name` varchar(150) DEFAULT NULL,
  `commercial_contact_email` varchar(100) DEFAULT NULL,
  `commercial_contact_phone` varchar(45) DEFAULT NULL,
  `risk_cla_id` int NOT NULL,
  `immediate_delivery_cla_id` int NOT NULL DEFAULT '0',
  `contract` text,
  `usr_id_create` int DEFAULT NULL,
  `usr_id_last_update` int DEFAULT NULL,
  `last_update_date` datetime DEFAULT NULL,
  `scheduling_cla_id` int DEFAULT NULL,
  `conta_azul_triggered` tinyint DEFAULT NULL,
  `cluster_name` varchar(15) DEFAULT NULL,
  `conta_azul_amendments` tinyint DEFAULT NULL,
  `signature_contact` tinyint DEFAULT '0',
  `basic_contact` tinyint DEFAULT NULL,
  `signature_cla_id` int DEFAULT NULL,
  `customer_name` varchar(255) DEFAULT NULL,
  `customer_email` varchar(255) DEFAULT NULL,
  `customer_phone` varchar(45) DEFAULT NULL,
  `finished_without_sale_cla_id` int DEFAULT NULL,
  `finished_without_sale_comment` text,
  `backoffice_rejected_comment` text,
  `coparticipation_internal_commission` tinyint DEFAULT NULL,
  `proposal_sent_date` datetime DEFAULT NULL,
  `proposal_sent` tinyint DEFAULT NULL,
  `revenue_amendments` tinyint DEFAULT NULL,
  `totvs_triggered` tinyint DEFAULT NULL,
  PRIMARY KEY (`pps_id`),
  UNIQUE KEY `ukNumCod` (`num`,`cod`),
  KEY `fk_proposal_lead1_idx` (`led_id`),
  KEY `fk_proposal_classifier_idx` (`status_cla_id`),
  KEY `fk_proposal_classifier_risk_idx` (`risk_cla_id`),
  KEY `fk_proposal_amendments_status_idx` (`amendments_status_cla`),
  KEY `fk_proposal_usr_id_create` (`usr_id_create`),
  KEY `fk_proposal_usr_id_last_update` (`usr_id_last_update`),
  KEY `fk_proposal_classifier_scheduling_idx` (`scheduling_cla_id`),
  KEY `fk_proposal_classifier_signature_cla_id_idx` (`signature_cla_id`),
  KEY `fk_proposal_immediate_delivery` (`immediate_delivery_cla_id`),
  KEY `fk_proposal_pps_id_production` (`pps_id_production`),
  KEY `fk_finished_without_sale_idx` (`finished_without_sale_cla_id`),
  CONSTRAINT `fk_finished_without_sale` FOREIGN KEY (`finished_without_sale_cla_id`) REFERENCES `classifier` (`cla_id`),
  CONSTRAINT `fk_proposal_amendments_status` FOREIGN KEY (`amendments_status_cla`) REFERENCES `classifier` (`cla_id`),
  CONSTRAINT `fk_proposal_classifier` FOREIGN KEY (`status_cla_id`) REFERENCES `classifier` (`cla_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_proposal_classifier_risk` FOREIGN KEY (`risk_cla_id`) REFERENCES `classifier` (`cla_id`),
  CONSTRAINT `fk_proposal_classifier_scheduling_idx` FOREIGN KEY (`scheduling_cla_id`) REFERENCES `classifier` (`cla_id`),
  CONSTRAINT `fk_proposal_classifier_signature_cla_id` FOREIGN KEY (`signature_cla_id`) REFERENCES `classifier` (`cla_id`),
  CONSTRAINT `fk_proposal_immediate_delivery` FOREIGN KEY (`immediate_delivery_cla_id`) REFERENCES `classifier` (`cla_id`),
  CONSTRAINT `fk_proposal_lead1` FOREIGN KEY (`led_id`) REFERENCES `lead` (`led_id`),
  CONSTRAINT `fk_proposal_pps_id_production` FOREIGN KEY (`pps_id_production`) REFERENCES `proposal` (`pps_id`),
  CONSTRAINT `fk_proposal_usr_id_create` FOREIGN KEY (`usr_id_create`) REFERENCES `user` (`usr_id`),
  CONSTRAINT `fk_proposal_usr_id_last_update` FOREIGN KEY (`usr_id_last_update`) REFERENCES `user` (`usr_id`)
) ENGINE=InnoDB AUTO_INCREMENT=23205 DEFAULT CHARSET=utf8mb3;


-- carbon.proposal_detail definition

CREATE TABLE `proposal_detail` (
  `ppd_id` int NOT NULL AUTO_INCREMENT,
  `pps_id` int NOT NULL,
  `sel_id` int NOT NULL,
  `intern_sale_sel_id` int DEFAULT NULL,
  `chn_id` int NOT NULL,
  `ptn_id` int DEFAULT NULL,
  `usr_id` int DEFAULT NULL,
  `purchase_order_service` varchar(50) DEFAULT NULL,
  `purchase_order_product` varchar(50) DEFAULT NULL,
  `purchase_order_documentation` varchar(50) DEFAULT NULL,
  `internal_comission` decimal(13,2) NOT NULL DEFAULT '0.00',
  `intern_sale_additive` int DEFAULT NULL,
  `seller_additive` int DEFAULT NULL,
  `sale_date_additive` datetime DEFAULT NULL,
  PRIMARY KEY (`ppd_id`),
  UNIQUE KEY `pps_id_UNIQUE` (`pps_id`),
  KEY `fk_proposal_detail_proposal1_idx` (`pps_id`),
  KEY `fk_proposal_detail_channel1_idx` (`chn_id`),
  KEY `fk_proposal_detail_partner1_idx` (`ptn_id`),
  KEY `fk_propossal_detail_usr_idx` (`usr_id`),
  KEY `fk_proposal_detail_internal_sale_idx` (`intern_sale_sel_id`),
  KEY `fk_proposal_detail_seller_idx` (`sel_id`),
  KEY `fk_proposal_detail_intern_sale_additive_idx` (`intern_sale_additive`),
  KEY `fk_proposal_detail_seller_additive_idx` (`seller_additive`),
  CONSTRAINT `fk_proposal_detail_channel1` FOREIGN KEY (`chn_id`) REFERENCES `channel` (`chn_id`),
  CONSTRAINT `fk_proposal_detail_interal_sale` FOREIGN KEY (`intern_sale_sel_id`) REFERENCES `seller` (`sel_id`),
  CONSTRAINT `fk_proposal_detail_intern_sale_additive_idx` FOREIGN KEY (`intern_sale_additive`) REFERENCES `seller` (`sel_id`),
  CONSTRAINT `fk_proposal_detail_partner1` FOREIGN KEY (`ptn_id`) REFERENCES `partner` (`ptn_id`),
  CONSTRAINT `fk_proposal_detail_proposal1` FOREIGN KEY (`pps_id`) REFERENCES `proposal` (`pps_id`),
  CONSTRAINT `fk_proposal_detail_seller` FOREIGN KEY (`sel_id`) REFERENCES `seller` (`sel_id`),
  CONSTRAINT `fk_proposal_detail_seller_additive` FOREIGN KEY (`seller_additive`) REFERENCES `seller` (`sel_id`)
) ENGINE=InnoDB AUTO_INCREMENT=23173 DEFAULT CHARSET=utf8mb3;


-- carbon.proposal_detail_vehicle definition

CREATE TABLE `proposal_detail_vehicle` (
  `pdv_id` int NOT NULL AUTO_INCREMENT,
  `ppd_id` int NOT NULL,
  `vhe_id` int DEFAULT NULL,
  `mdl_id` int NOT NULL,
  `version` varchar(100) DEFAULT NULL,
  `model_year` int NOT NULL,
  `ppr_id` int NOT NULL,
  `product_amount_discount` decimal(13,2) NOT NULL DEFAULT '0.00',
  `product_percent_discount` decimal(5,2) NOT NULL DEFAULT '0.00',
  `product_final_price` decimal(13,2) NOT NULL DEFAULT '0.00',
  `product_table_price_tax` decimal(13,2) DEFAULT NULL,
  `over_price` decimal(13,2) NOT NULL,
  `over_price_carbon` decimal(13,2) DEFAULT NULL,
  `over_price_partner_discount_amount` decimal(13,2) NOT NULL,
  `over_price_partner_discount_percent` decimal(5,2) NOT NULL,
  `price_discount_amount` decimal(13,2) NOT NULL,
  `price_discount_percent` decimal(5,2) NOT NULL,
  `total_amount` decimal(13,2) NOT NULL,
  `total_tax_amount` decimal(13,2) NOT NULL,
  `total_tax_percent` decimal(5,2) NOT NULL,
  `standard_term_days` int NOT NULL,
  `agreed_term_days` int NOT NULL,
  `spc_id` int DEFAULT NULL,
  `spc_tax` decimal(8,4) DEFAULT NULL,
  `spc_id_ammendment` int DEFAULT NULL,
  `spc_ammendment_tax` decimal(8,4) DEFAULT NULL,
  `over_price_carbon_ammendment` decimal(13,2) DEFAULT NULL,
  `price_discount_amount_ammendment` decimal(13,2) DEFAULT NULL,
  `over_price_ammendment` decimal(13,2) DEFAULT NULL,
  `over_price_partner_discount_amount_ammendment` decimal(13,2) DEFAULT NULL,
  PRIMARY KEY (`pdv_id`),
  KEY `fk_proposal_detail_vehicle_proposal_detail1_idx` (`ppd_id`),
  KEY `fk_proposal_detail_vehicle_vehicle1_idx` (`vhe_id`),
  KEY `fk_proposal_detail_vehicle_product_price_list1_idx` (`ppr_id`),
  KEY `fk_proposal_detail_vehicle_model_idx` (`mdl_id`),
  KEY `fk_specific_payment_condition` (`spc_id`),
  KEY `fk_specific_payment_condition_ammendment` (`spc_id_ammendment`),
  CONSTRAINT `fk_proposal_detail_vehicle_model` FOREIGN KEY (`mdl_id`) REFERENCES `model` (`mdl_id`),
  CONSTRAINT `fk_proposal_detail_vehicle_product_price_list1` FOREIGN KEY (`ppr_id`) REFERENCES `price_product` (`ppr_id`),
  CONSTRAINT `fk_proposal_detail_vehicle_proposal_detail1` FOREIGN KEY (`ppd_id`) REFERENCES `proposal_detail` (`ppd_id`),
  CONSTRAINT `fk_proposal_detail_vehicle_vehicle1` FOREIGN KEY (`vhe_id`) REFERENCES `vehicle` (`vhe_id`),
  CONSTRAINT `fk_specific_payment_condition` FOREIGN KEY (`spc_id`) REFERENCES `specific_payment_condition` (`spc_id`),
  CONSTRAINT `fk_specific_payment_condition_ammendment` FOREIGN KEY (`spc_id_ammendment`) REFERENCES `specific_payment_condition` (`spc_id`)
) ENGINE=InnoDB AUTO_INCREMENT=23098 DEFAULT CHARSET=utf8mb3;