spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/carbon?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Yoshin@8912
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format-sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

# JWT Configuration
jwt:
  secret: chave_secreta_muito_longa_para_garantir_seguranca_adequada_do_jwt
